= Reactor 3 参考文档
Stephane Maldini <https://twitter.com/smaldini[@smaldini]>; Simon Baslé <https://twitter.com/simonbasle[@simonbasle]>
:appversion: 3.1.4.RELEASE
ifndef::host-github[:ext-relative: {outfilesuffix}]
{appversion}
:doctype: book
:icons: font
:toc:
:sectnums:
:sectanchors:
:linkattrs:

NOTE: （译者加）本文档的一些典型的名词如下：
* `Publisher`（发布者）、`Subscriber`（订阅者）、`Subscription`（订阅 n.）、`subscribe`（订阅 v.）。
* `event`/`signal`（事件/信号，不爽的是原文经常甚至在一个句子将两个词来回用，但表示的意思是相同的，
因此如果你看到本文翻译有时候用事件，有时候用信号，在本文档内可以认为一个意思）。
* `sequence`/`stream`（序列/流，两个词意思相似，本文介绍的是响应式流的内容，但是出现比较多的是
sequence这个词，主要翻译为“序列”，有些地方为了更加契合且方便理解翻译为“流序列”）。
* `element`/`item`（主要指序列中的元素，文中两个词基本翻译为“元素”）。
* `emit`/`produce`/`generate`（发出/生产/生成，文中这三个英文词也有相似之处，对于 emit 多翻译为
“发出”，对于后两个多翻译为“生成”，因为感觉用“生产”比较奇怪）、`consume`（消费）。
* `Processor`（未做翻译，保留英文，一种 `Publisher` 和 `Subscriber` 的综合体）。
* `operator`（译作操作符，声明式的可组装的响应式方法，其组装成的链译作“操作链”）。

include::aboutDoc.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/reactor/reactor-core/edit/master/src/docs/asciidoc/aboutDoc.adoc[Suggest Edit^, title="Suggest an edit to the above section via github", role="fa fa-edit"]
to "<<about-doc>>"
endif::[]

include::gettingStarted.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/reactor/reactor-core/edit/master/src/docs/asciidoc/gettingStarted.adoc[Suggest Edit, title="Suggest an edit to the above section via github", role="fa fa-edit"]
to "<<getting-started>>"
endif::[]

include::reactiveProgramming.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/reactor/reactor-core/edit/master/src/docs/asciidoc/reactiveProgramming.adoc[Suggest Edit, title="Suggest an edit to the above section via github", role="fa fa-edit"]
to "<<intro-reactive>>"
endif::[]

include::coreFeatures.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/reactor/reactor-core/edit/master/src/docs/asciidoc/coreFeatures.adoc[Suggest Edit, title="Suggest an edit to the above section via github", role="fa fa-edit"]
to "<<core-features>>"
endif::[]

//TODO see other sections from consuming.adoc

include::kotlin.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/reactor/reactor-core/edit/master/src/docs/asciidoc/kotlin.adoc[Suggest Edit, title="Suggest an edit to the above section via github", role="fa fa-edit"]
to "<<kotlin>>"
endif::[]

include::testing.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/reactor/reactor-core/edit/master/src/docs/asciidoc/testing.adoc[Suggest Edit, title="Suggest an edit to the above section via github", role="fa fa-edit"]
to "<<testing>>"
endif::[]

include::debugging.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/reactor/reactor-core/edit/master/src/docs/asciidoc/debugging.adoc[Suggest Edit, title="Suggest an edit to the above section via github", role="fa fa-edit"]
to "<<debugging>>"
endif::[]

include::advancedFeatures.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/reactor/reactor-core/edit/master/src/docs/asciidoc/advancedFeatures.adoc[Suggest Edit, title="Suggest an edit to the above section via github", role="fa fa-edit"]
to "<<advanced>>"
endif::[]


[appendix]
include::operatorChoice.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/reactor/reactor-core/edit/master/src/docs/asciidoc/apdx-operatorChoice.adoc[Suggest Edit, title="Suggest an edit to the above section via github", role="fa fa-edit"]
to "<<which-operator>>"
endif::[]

[appendix]
include::faq.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/reactor/reactor-core/edit/master/src/docs/asciidoc/faq.adoc[Suggest Edit, title="Suggest an edit to the above section via github", role="fa fa-edit"]
to "<<faq>>"
endif::[]

[appendix]
include::apdx-reactorExtra.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/reactor/reactor-core/edit/master/src/docs/asciidoc/apdx-reactorExtra.adoc[Suggest Edit, title="Suggest an edit to the above section via github", role="fa fa-edit"]
to "<<reactor-extra>>"
endif::[]

//TODO later add appendices about internals, writing operators, fusion
//[appendix]
//include::apdx-implem.adoc[]
//
//[appendix]
//include::apdx-writingOperator.adoc[]
//[appendix]
//include::apdx-optimizations.adoc[]

//TODO later add appendix about migrating from RxJava?
//[appendix]
//include::apdx-migrating.adoc[]