= Reactor 3 参考文档
Stephane Maldini <https://twitter.com/smaldini[@smaldini]>; Simon Baslé <https://twitter.com/simonbasle[@simonbasle]>
:appversion: 3.1.4.RELEASE
ifndef::host-github[:ext-relative: {outfilesuffix}]
{appversion}
:doctype: book
:icons: font
:toc:
:sectnums:
:sectanchors:
:linkattrs:

[NOTE]
====
（译者加）本文档的一些典型的名词如下：

* `Publisher`（发布者）、`Subscriber`（订阅者）、`Subscription`（订阅 n.）、`subscribe`（订阅 v.）。
* `event`/`signal`（事件/信号，原文常甚至在一个句子将两个词来回用，但表示的意思是基本相同的，
因此如果你看到本文翻译有时候用事件，有时候用信号，在本文档内基本可以认为一个意思）。
* `sequence`/`stream`（序列/流，两个词意思相似，本文介绍的是响应式流的内容，但是出现比较多的是
sequence这个词，主要翻译为“序列”，有些地方为了更加契合且方便理解翻译为“流序列”）。
* `element`/`item`（主要指序列中的元素，文中两个词基本翻译为“元素”）。
* `emit`/`produce`/`generate`（发出/产生/生成，文中这三个英文词也有相似之处，对于 emit 多翻译为
“发出”，对于后两个多翻译为“生成”）、`consume`（消费）。
* `Processor`（未做翻译，保留英文）。
* `operator`（译作操作符，声明式的可组装的响应式方法，其组装成的链译作“操作链”）。
====

include::aboutDoc.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/get-set/reactor-core/edit/master-zh/src/docs/asciidoc/aboutDoc.adoc[翻译建议^, title="通过Github的编辑功能对以上翻译内容提出建议", role="fa fa-edit"]
- "<<about-doc>>"
endif::[]

include::gettingStarted.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/get-set/reactor-core/edit/master-zh/src/docs/asciidoc/gettingStarted.adoc[翻译建议, title="通过Github的编辑功能对以上翻译内容提出建议", role="fa fa-edit"]
- "<<getting-started>>"
endif::[]

include::reactiveProgramming.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/get-set/reactor-core/edit/master-zh/src/docs/asciidoc/reactiveProgramming.adoc[翻译建议, title="通过Github的编辑功能对以上翻译内容提出建议", role="fa fa-edit"]
- "<<intro-reactive>>"
endif::[]

include::coreFeatures.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/get-set/reactor-core/edit/master-zh/src/docs/asciidoc/coreFeatures.adoc[翻译建议, title="通过Github的编辑功能对以上翻译内容提出建议", role="fa fa-edit"]
- "<<core-features>>"
endif::[]

//TODO see other sections from consuming.adoc

include::kotlin.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/get-set/reactor-core/edit/master-zh/src/docs/asciidoc/kotlin.adoc[翻译建议, title="通过Github的编辑功能对以上翻译内容提出建议", role="fa fa-edit"]
- "<<kotlin>>"
endif::[]

include::testing.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/get-set/reactor-core/edit/master-zh/src/docs/asciidoc/testing.adoc[翻译建议, title="通过Github的编辑功能对以上翻译内容提出建议", role="fa fa-edit"]
- "<<testing>>"
endif::[]

include::debugging.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/get-set/reactor-core/edit/master-zh/src/docs/asciidoc/debugging.adoc[翻译建议, title="通过Github的编辑功能对以上翻译内容提出建议", role="fa fa-edit"]
- "<<debugging>>"
endif::[]

include::advancedFeatures.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/get-set/reactor-core/edit/master-zh/src/docs/asciidoc/advancedFeatures.adoc[翻译建议, title="通过Github的编辑功能对以上翻译内容提出建议", role="fa fa-edit"]
- "<<advanced>>"
endif::[]


[appendix]
include::apdx-operatorChoice.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/get-set/reactor-core/edit/master-zh/src/docs/asciidoc/apdx-operatorChoice.adoc[翻译建议, title="通过Github的编辑功能对以上翻译内容提出建议", role="fa fa-edit"]
- "<<which-operator>>"
endif::[]

[appendix]
include::faq.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/get-set/reactor-core/edit/master-zh/src/docs/asciidoc/faq.adoc[翻译建议, title="通过Github的编辑功能对以上翻译内容提出建议", role="fa fa-edit"]
- "<<faq>>"
endif::[]

[appendix]
include::apdx-reactorExtra.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/get-set/reactor-core/edit/master-zh/src/docs/asciidoc/apdx-reactorExtra.adoc[翻译建议, title="通过Github的编辑功能对以上翻译内容提出建议", role="fa fa-edit"]
- "<<reactor-extra>>"
endif::[]

//TODO later add appendices about internals, writing operators, fusion
//[appendix]
//include::apdx-implem.adoc[]
//
//[appendix]
//include::apdx-writingOperator.adoc[]
//[appendix]
//include::apdx-optimizations.adoc[]

//TODO later add appendix about migrating from RxJava?
//[appendix]
//include::apdx-migrating.adoc[]