Processors 既是一种特别的发布者（`Publisher`）又是一种订阅者（`Subscriber`）。
那意味着你可以
订阅一个 `Processor`（通常它们会实现 `Flux`），也可以调用相关方法来手动
插入数据到序列，或终止序列。

Processor 有多种类型，它们都有特别的语义规则，但是在你研究它们之前，最好问一下
自己如下几个问题：

= 我是否需要使用 Processor？
多数情况下，你应该进行避免使用 `Processor`，它们较难正确使用，主要用于一些特殊场景下。

如果你觉得 `Processor` 适合你的使用场景，请首先看一下是否尝试过以下两种替代方式：

. 是否有一个或多个 operator 的组合能够满足需求？（见 <<which-operator>>）
. <<producing,"generator">> operator 是否能解决问题？（通常这些 operators
可以用来桥接非响应式的 API，它们提供了一个“sink”，在生成数据流序列方面，
概念上类似于 `Processor`）

如果看了以上替代方案，你仍然觉得需要一个 `Processor`，阅读 <<processor-overview>>
这一节来了解一下不同的实现吧。

= 使用 `Sink` 门面对象来线程安全地生成流
比起直接使用 Reactor 的 `Processors`，更好的方式是通过调用一次 `sink()`
来得到 `Processor` 的 `Sink`。

`FluxProcessor` 的 sink 是线程安全的“生产者（producer）”，因此能够在应用程序中
多线程并发地生成数据。例如，一个线程安全的序列化（serialized）的 sink 能够通过
`UnicastProcessor` 创建：

[source,java]
----
UnicastProcessor<Integer> processor = UnicastProcessor.create();
FluxSink<Integer> sink = processor.sink(overflowStrategy);
----

多个生产者线程可以并发地生成数据到以下的序列化 sink。

[source,java]
----
sink.next(n);
----

根据 `Processor` 及其配置，`next` 产生的溢出有两种可能的处理方式：

* 一个无限的 processor 通过丢弃或缓存自行处理溢出。
* 一个有限的 processor 阻塞在 `IGNORE` 策略，或将 `overflowStrategy`
应用于 `sink`。


[[processor-overview]]
= 现有的 Processors 总览
Reactor Core 内置多种 `Processor`。这些 processor 具有不同的语法，大概分为三类。
下边简要介绍一下这三种 processor：

* *直接的（direct）* （`DirectProcessor` 和 `UnicastProcessor`）：这些 processors 只能通过直接
调用 `Sink` 的方法来推送数据。
* *同步的（synchronous）* （`EmitterProcessor` 和 `ReplayProcessor`）：这些 processors 既可以
直接调用 `Sink` 方法来推送数据，也可以通过订阅到一个上游的发布者来同步地产生数据。
* *异步的（asynchronous）* （`WorkQueueProcessor` 和 `TopicProcessor`）：这些 processors
可以将从多个上游发布者得到的数据推送下去。由于使用了 `RingBuffer` 的数据结构来
缓存多个来自上游的数据，因此更加有健壮性。

异步的 processor 在实例化的时候最复杂，因为有许多不同的选项。因此它们暴露出一个 `Builder` 接口。
而简单的 processors 有静态的工厂方法。

== DirectProcessor
`DirectProcessor` 可以将信号分发给零到多个订阅者（`Subscriber`）。它是最容易实例化的，使用静态方法
`create()` 即可。另一方面，*它的不足是无法处理背压*。所以，当 `DirectProcessor` 推送的是 N
个元素，而至少有一个订阅者的请求个数少于 N 的时候，就会发出一个 `IllegalStateException`。

一旦 `Processor` 终止（通常通过调用它的 `Sink` 的 `error(Throwable)` 或 `complete()` 方法），
虽然它允许更多的订阅者订阅它，但是会立即向它们重新发送终止信号。

== UnicastProcessor
`UnicastProcessor` 可以使用一个内置的缓存来处理背压。代价就是它最多只能有一个订阅者。

`UnicastProcessor` 有多种选项，因此提供多种不同的 `create` 静态方法。例如，它默认是
_无限的（unbounded）_ ：如果你在在订阅者还没有请求数据的情况下让它推送数据，它会缓存所有数据。

可以通过提供一个自定义的 `Queue` 的具体实现传递给 `create` 工厂方法来改变默认行为。如果给出的队列是
有限的（bounded）， 并且缓存已满，而且未收到下游的请求，processor 会拒绝推送数据。

在上边 _有限的_ 例子中，还可以在构造 processor 的时候提供一个回调方法，这个回调方法可以在每一个
被拒绝推送的元素上调用，从而让开发者有机会清理这些元素。

== EmitterProcessor
`EmitterProcessor` 能够向多个订阅者发送数据，并且可以对每一个订阅者进行背压处理。它本身也可以订阅一个
`Publisher` 并同步获得数据。

最初如果没有订阅者，它仍然允许推送一些数据到缓存，缓存大小由 `bufferSize` 定义。
之后如果仍然没有订阅者订阅它并消费数据，对 `onNext` 的调用会阻塞，直到有订阅者接入
（这时只能并发地订阅了）。

因此第一个订阅者会收到最多 `bufferSize` 个元素。然而之后， processor 不会重新发送（replay）
数据给后续的订阅者。这些后续接入的订阅者只能获取到它们开始订阅 *之后* 推送的数据。这个内部的
缓存会继续用于背压的目的。

默认情况下，如果所有的订阅者都取消了（基本意味着它们都不再订阅（un-subscribed）了），
它会清空内部缓存，并且不再接受更多的订阅者。这一点可以通过 `create` 静态工厂方法的
`autoCancel` 参数来配置。

== ReplayProcessor
`ReplayProcessor` 会缓存直接通过自身的 `Sink` 推送的元素，以及来自上游发布者的元素，
并且后来的订阅者也会收到重发（replay）的这些元素。

可以通过多种配置方式创建它：

* 缓存一个元素（`cacheLast`）。
* 缓存一定个数的历史元素（`create(int)`），所有的历史元素（`create()`）。
* 缓存基于时间窗期间内的元素（`createTimeout(Duration)`）。
* 缓存基于历史个数和时间窗的元素（`createSizeOrTimeout(int, Duration)`）。

== TopicProcessor
`TopicProcessor` 是一个异步的 processor，它能够重发来自多个上游发布者的元素，
这需要在创建它的时候配置 `shared` （见 `build()` 的 `share(boolean)` 配置）。

注意，如果你企图在并发环境下通过并发的上游 Publisher 调用 `TopicProcessor` 的 `onNext`、
`onComplete`，或 `onError` 方法，就必须配置 shared。

否则，并发调用就是非法的，从而 processor 是完全兼容响应式流规范的。

`TopicProcessor` 能够对多个订阅者发送数据。它通过对每一个订阅者关联一个线程来实现这一点，
这个线程会一直执行直到 processor 发出 `onError` 或 `onComplete` 信号，或关联的订阅者被取消。
最多可以接受的订阅者个数由构造者方法 `executor` 指定，通过提供一个有限线程数的 `ExecutorService`
来限制这一个数。

这个 processor 基于一个 `RingBuffer` 数据结构来存储已发送的数据。每一个订阅者线程
自行管理其相关的数据在 `RingBuffer` 中的索引。

这个 processor 也有一个 `autoCancel` 构造器方法：如果设置为 `true` （默认的），那么当
所有的订阅者取消之后，源 `Publisher`(s) 也就被取消了。

== WorkQueueProcessor
`WorkQueueProcessor` 也是一个异步的 processor，也能够重发来自多个上游发布者的元素，
同样在创建时需要配置 `shared` （它多数构造器配置与 `TopicProcessor` 相同）。

它放松了对响应式流规范的兼容，但是好处就在于相对于 `TopicProcessor` 来说需要更少的资源。
它仍然基于 `RingBuffer`，但是不再要求每一个订阅者都关联一个线程，因此相对于 `TopicProcessor`
来说更具扩展性。

代价在于分发模式有些区别：来自订阅者的请求会汇总在一起，并且这个 processor 每次只对一个
订阅者发送数据，因此需要循环（round-robin）对订阅者发送数据，而不是一次全部发出的模式。

NOTE: 无法保证完全公平的循环分发。

`WorkQueueProcessor` 多数构造器方法与 `TopicProcessor` 相同，比如 `autoCancel`、`share`，
以及 `waitStrategy`。下游订阅者的最大数目同样由构造器 `executor` 配置的 `ExecutorService`
决定。

WARNING: 你最好注意不要有太多订阅者订阅 `WorkQueueProcessor`，因为这 *会锁住 processor*。
如果你需要限制订阅者数量，最好使用一个 `ThreadPoolExecutor` 或 `ForkJoinPool`。这个
processor 能够检测到（线程池）容量并在订阅者过多时抛出异常。

//TODO == MonoProcessor
