=== `subscribe` 方法示例

这一小节包含了对 `subscribe` 的5个不同签名的方法的示例，如下是一个无参的基本方法的使用：

[source,java]
----
Flux<Integer> ints = Flux.range(1, 3); <1>
ints.subscribe(); <2>
----

<1> 配置一个在订阅时会产生3个值的 `Flux`。
<2> 最简单的订阅方式。

第二行代码没有任何输出，但是它确实执行了。`Flux` 产生了3个值。如果我们传入一个 lambda，
我们就可以看到这几个值，如下一个列子：

[source,java]
----
Flux<Integer> ints = Flux.range(1, 3); <1>
ints.subscribe(i -> System.out.println(i)); <2>
----

<1> 配置一个在订阅时会产生3个值的 `Flux`。
<2> 订阅它并打印值。

第二行代码会输入如下内容：

----
1
2
3
----

为了演示下一个方法签名，我们故意引入一个错误，如下所示：

[source, java]
----
Flux<Integer> ints = Flux.range(1, 4) <1>
      .map(i -> { <2>
        if (i <= 3) return i; <3>
        throw new RuntimeException("Got to 4"); <4>
      });
ints.subscribe(i -> System.out.println(i), <5>
      error -> System.err.println("Error: " + error));
----

<1> 配置一个在订阅时会产生4个值的 `Flux`。
<2> 为了对元素进行处理，我们需要一个 map 操作。
<3> 对于多数元素，返回值本身。
<4> 对其中一个元素抛出错误。
<5> 订阅的时候定义如何进行错误处理。

现在我们有两个 lambda 表达式：一个是用来处理正常数据，一个用来处理错误。
刚才的代码输出如下：

----
1
2
3
Error: java.lang.RuntimeException: Got to 4
----

下一个 `subscribe` 方法的签名既有错误处理，还有一个完成后的处理，如下：

[source,java]
----
Flux<Integer> ints = Flux.range(1, 4); <1>
ints.subscribe(i -> System.out.println(i),
    error -> System.err.println("Error " + error),
    () -> {System.out.println("Done");}); <2>
----

<1> 配置一个在订阅时会产生4个值的 `Flux`。
<2> 订阅时定义错误和完成信号的处理。

错误和完成信号都是终止信号，并且二者只会出现其中之一。为了能够最终全部正常完成，你必须处理错误信号。

用于处理完成信号的 lambda 是一对空的括号，因为它实际上匹配的是 `Runnalbe` 接口中的 `run` 方法，
不接受参数。刚才的代码输出如下：

----
1
2
3
4
Done
----

最后一个 `subscribe` 方法签名包含一个自定义的 `subscriber`（下一节会介绍到）：

[source,java]
----
SampleSubscriber<Integer> ss = new SampleSubscriber<Integer>();
Flux<Integer> ints = Flux.range(1, 4);
ints.subscribe(i -> System.out.println(i),
    error -> System.err.println("Error " + error),
    () -> {System.out.println("Done");},
    s -> ss.request(10));
ints.subscribe(ss);
----

上面这个例子中，我们把一个自定义的 `Subscriber` 作为 `subscribe` 方法的最后一个参数。
下边的例子是这个自定义的 `Subscriber`，这是一个对 `Subscriber` 的最简单实现：

[source,java]
----
package io.projectreactor.samples;

import org.reactivestreams.Subscription;

import reactor.core.publisher.BaseSubscriber;

public class SampleSubscriber<T> extends BaseSubscriber<T> {

	public void hookOnSubscribe(Subscription subscription) {
		System.out.println("Subscribed");
		request(1);
	}

	public void hookOnNext(T value) {
		System.out.println(value);
		request(1);
	}
}
----

`SampleSubscriber` 类继承自 `BaseSubscriber`，在 Reactor 中, 推荐用户扩展它来实现自定义的
`Subscriber`。这个类提供了一些 hook 方法，我们可以通过重写它们来调整 subscriber 的行为。
默认情况下，它会触发一个无限个数的请求，但是当你想自定义请求元素的个数的时候，扩展
`BaseSubscriber` 就很方便了。

扩展的时候通常至少要覆盖 `hookOnSubscribe(Subscription subscription)` 和 `hookOnNext(T value)`
这两个方法。这个例子中， `hookOnSubscribe` 方法打印一段话到标准输出，然后进行第一次请求。
然后 `hookOnNext` 同样进行了打印，同时逐个处理剩余请求。

`SampleSubscriber` 输出如下：

----
Subscribed
1
2
3
4
----

NOTE: 建议你同时重写 `hookOnError`、`hookOnCancel`，以及 `hookOnComplete` 方法。
你最好也重写 `hookFinally` 方法。`SampleSubscribe` 确实是一个最简单的实现了
请求有限个数元素的 `Subscriber`。

本文档后边还会再讨论 `BaseSubscriber`。